template<>
class ABIDefs<ExecModeMipsel32> {
public:
    typedef uint32_t Tpointer_t;
    typedef int8_t   Tchar;
    typedef uint8_t  Tuchar;
    typedef int16_t  Tshort;
    typedef uint16_t Tushort;
    typedef int32_t  Tint;
    typedef uint32_t Tuint;
    typedef int32_t  Tlong;
    typedef uint32_t Tulong;
    typedef int64_t  Tllong;
    typedef int32_t  Tssize_t;
    typedef int32_t  Tptrdiff_t;
    typedef uint32_t Tsize_t;
    static const Tint VSTDIN_FILENO = 0x00000000;
    static const Tint VSTDOUT_FILENO = 0x00000001;
    static const Tint VSTDERR_FILENO = 0x00000002;
    typedef int32_t  Tpid_t;
    static const Tint VEPERM = 0x00000001;
    static const Tint VENOENT = 0x00000002;
    static const Tint VESRCH = 0x00000003;
    static const Tint VEINTR = 0x00000004;
    static const Tint VEIO = 0x00000005;
    static const Tint VENXIO = 0x00000006;
    static const Tint VE2BIG = 0x00000007;
    static const Tint VENOEXEC = 0x00000008;
    static const Tint VEBADF = 0x00000009;
    static const Tint VECHILD = 0x0000000a;
    static const Tint VEAGAIN = 0x0000000b;
    static const Tint VENOMEM = 0x0000000c;
    static const Tint VEACCES = 0x0000000d;
    static const Tint VEFAULT = 0x0000000e;
    static const Tint VENOTBLK = 0x0000000f;
    static const Tint VEBUSY = 0x00000010;
    static const Tint VEEXIST = 0x00000011;
    static const Tint VEXDEV = 0x00000012;
    static const Tint VENODEV = 0x00000013;
    static const Tint VENOTDIR = 0x00000014;
    static const Tint VEISDIR = 0x00000015;
    static const Tint VEINVAL = 0x00000016;
    static const Tint VENFILE = 0x00000017;
    static const Tint VEMFILE = 0x00000018;
    static const Tint VENOTTY = 0x00000019;
    static const Tint VETXTBSY = 0x0000001a;
    static const Tint VEFBIG = 0x0000001b;
    static const Tint VENOSPC = 0x0000001c;
    static const Tint VESPIPE = 0x0000001d;
    static const Tint VEROFS = 0x0000001e;
    static const Tint VEMLINK = 0x0000001f;
    static const Tint VEPIPE = 0x00000020;
    static const Tint VEDOM = 0x00000021;
    static const Tint VERANGE = 0x00000022;
    static const Tint VENOSYS = 0x00000059;
    static const Tint VELOOP = 0x0000005a;
    static const Tint VEAFNOSUPPORT = 0x0000007c;
    static const Tint VSIGHUP = 0x00000001;
    static const Tint VSIGINT = 0x00000002;
    static const Tint VSIGQUIT = 0x00000003;
    static const Tint VSIGILL = 0x00000004;
    static const Tint VSIGTRAP = 0x00000005;
    static const Tint VSIGABRT = 0x00000006;
    static const Tint VSIGFPE = 0x00000008;
    static const Tint VSIGKILL = 0x00000009;
    static const Tint VSIGBUS = 0x0000000a;
    static const Tint VSIGSEGV = 0x0000000b;
    static const Tint VSIGPIPE = 0x0000000d;
    static const Tint VSIGALRM = 0x0000000e;
    static const Tint VSIGTERM = 0x0000000f;
    static const Tint VSIGUSR1 = 0x00000010;
    static const Tint VSIGUSR2 = 0x00000011;
    static const Tint VSIGCHLD = 0x00000012;
    static const Tint VSIGSTOP = 0x00000017;
    static const Tint VSIGTSTP = 0x00000018;
    static const Tint VSIGCONT = 0x00000019;
    static const Tint VCSIGNAL = 0x000000ff;
    static const Tint VCLONE_VM = 0x00000100;
    static const Tint VCLONE_FS = 0x00000200;
    static const Tint VCLONE_FILES = 0x00000400;
    static const Tint VCLONE_SIGHAND = 0x00000800;
    static const Tint VCLONE_VFORK = 0x00004000;
    static const Tint VCLONE_PARENT = 0x00008000;
    static const Tint VCLONE_THREAD = 0x00010000;
    static const Tint VCLONE_NEWNS = 0x00020000;
    static const Tint VCLONE_SYSVSEM = 0x00040000;
    static const Tint VCLONE_SETTLS = 0x00080000;
    static const Tint VCLONE_PARENT_SETTID = 0x00100000;
    static const Tint VCLONE_CHILD_CLEARTID = 0x00200000;
    static const Tint VCLONE_DETACHED = 0x00400000;
    static const Tint VCLONE_UNTRACED = 0x00800000;
    static const Tint VCLONE_CHILD_SETTID = 0x01000000;
    static const Tint VCLONE_STOPPED = 0x02000000;
    static const Tint VWNOHANG = 0x00000001;
    static const Tint VWUNTRACED = 0x00000002;
    static const Tint VFUTEX_PRIVATE_FLAG = 0x00000080;
    static const Tint VFUTEX_CLOCK_REALTIME = 0x00000100;
    static const Tint VFUTEX_CMD_MASK = ~Tint(0x00000180);
    static const Tint VFUTEX_WAIT = 0x00000000;
    static const Tint VFUTEX_WAKE = 0x00000001;
    static const Tint VFUTEX_FD = 0x00000002;
    static const Tint VFUTEX_REQUEUE = 0x00000003;
    static const Tint VFUTEX_CMP_REQUEUE = 0x00000004;
    static const Tint VFUTEX_WAKE_OP = 0x00000005;
    static const Tint VFUTEX_LOCK_PI = 0x00000006;
    static const Tint VFUTEX_UNLOCK_PI = 0x00000007;
    static const Tint VFUTEX_TRYLOCK_PI = 0x00000008;
    static const Tint VFUTEX_WAIT_BITSET = 0x00000009;
    static const Tint VFUTEX_WAKE_BITSET = 0x0000000a;
    static const Tuint VFUTEX_BITSET_MATCH_ANY = ~Tuint(0x00000000);
    static const Tint VFUTEX_OP_OPARG_SHIFT = 0x00000008;
    static const Tint VFUTEX_OP_SET = 0x00000000;
    static const Tint VFUTEX_OP_ADD = 0x00000001;
    static const Tint VFUTEX_OP_OR = 0x00000002;
    static const Tint VFUTEX_OP_ANDN = 0x00000003;
    static const Tint VFUTEX_OP_XOR = 0x00000004;
    static const Tint VFUTEX_OP_CMP_EQ = 0x00000000;
    static const Tint VFUTEX_OP_CMP_NE = 0x00000001;
    static const Tint VFUTEX_OP_CMP_LT = 0x00000002;
    static const Tint VFUTEX_OP_CMP_LE = 0x00000003;
    static const Tint VFUTEX_OP_CMP_GT = 0x00000004;
    static const Tint VFUTEX_OP_CMP_GE = 0x00000005;
    class Trobust_list {
    public:
        static const size_t Size_All=4;
        typedef Tpointer_t Type_next;
        static const size_t Offs_next=0;
    };
    class Trobust_list_head {
    public:
        static const size_t Size_All=12;
        typedef Trobust_list Type_list;
        static const size_t Offs_list=0;
        typedef Tlong Type_futex_offset;
        static const size_t Offs_futex_offset=4;
        typedef Tpointer_t Type_list_op_pending;
        static const size_t Offs_list_op_pending=8;
    };
    static const Tint VSA_NOCLDSTOP = 0x00000001;
    static const Tint VSA_NOCLDWAIT = 0x00010000;
    static const Tuint VSA_RESETHAND = ~Tuint(0x7fffffff);
    static const Tint VSA_ONSTACK = 0x08000000;
    static const Tint VSA_SIGINFO = 0x00000008;
    static const Tint VSA_RESTART = 0x10000000;
    static const Tint VSA_NODEFER = 0x40000000;
    static const Tint VSA_INTERRUPT = 0x20000000;
    static const Tpointer_t VSIG_DFL = 0x00000000;
    static const Tpointer_t VSIG_IGN = 0x00000001;
    static const Tint VSIG_BLOCK = 0x00000001;
    static const Tint VSIG_UNBLOCK = 0x00000002;
    static const Tint VSIG_SETMASK = 0x00000003;
    typedef int32_t  Tclock_t;
    class Ttms {
    public:
        static const size_t Size_All=16;
        typedef Tclock_t Type_tms_utime;
        static const size_t Offs_tms_utime=0;
        typedef Tclock_t Type_tms_stime;
        static const size_t Offs_tms_stime=4;
        typedef Tclock_t Type_tms_cutime;
        static const size_t Offs_tms_cutime=8;
        typedef Tclock_t Type_tms_cstime;
        static const size_t Offs_tms_cstime=12;
    };
    typedef int32_t  Ttime_t;
    typedef int32_t  Tsuseconds_t;
    class Ttimeval {
    public:
        static const size_t Size_All=8;
        typedef Ttime_t Type_tv_sec;
        static const size_t Offs_tv_sec=0;
        typedef Tsuseconds_t Type_tv_usec;
        static const size_t Offs_tv_usec=4;
    };
    class Ttimezone {
    public:
        static const size_t Size_All=8;
        typedef Tint Type_tz_minuteswest;
        static const size_t Offs_tz_minuteswest=0;
        typedef Tint Type_tz_dsttime;
        static const size_t Offs_tz_dsttime=4;
    };
    typedef int32_t  Tclockid_t;
    class Ttimespec {
    public:
        static const size_t Size_All=8;
        typedef Ttime_t Type_tv_sec;
        static const size_t Offs_tv_sec=0;
        typedef Tlong Type_tv_nsec;
        static const size_t Offs_tv_nsec=4;
    };
    typedef uint32_t Tuid_t;
    typedef uint32_t Tgid_t;
    static const Tuint VMAP_SHARED = 0x00000001;
    static const Tuint VMAP_PRIVATE = 0x00000002;
    static const Tuint VMAP_FIXED = 0x00000010;
    static const Tuint VMAP_ANONYMOUS = 0x00000800;
    static const Tint VPROT_NONE = 0x00000000;
    static const Tint VPROT_READ = 0x00000001;
    static const Tint VPROT_WRITE = 0x00000002;
    static const Tint VPROT_EXEC = 0x00000004;
    static const Tuint VMREMAP_MAYMOVE = 0x00000001;
    static const Tuint VMREMAP_FIXED = 0x00000002;
    static const Tint VO_ACCMODE = 0x00000003;
    static const Tint VO_RDONLY = 0x00000000;
    static const Tint VO_WRONLY = 0x00000001;
    static const Tint VO_RDWR = 0x00000002;
    static const Tint VO_APPEND = 0x00000008;
    static const Tint VO_SYNC = 0x00000010;
    static const Tint VO_NONBLOCK = 0x00000080;
    static const Tint VO_CREAT = 0x00000100;
    static const Tint VO_TRUNC = 0x00000200;
    static const Tint VO_EXCL = 0x00000400;
    static const Tint VO_NOCTTY = 0x00000800;
    static const Tint VO_ASYNC = 0x00001000;
    static const Tint VO_LARGEFILE = 0x00002000;
    static const Tint VO_DIRECT = 0x00008000;
    static const Tint VO_DIRECTORY = 0x00010000;
    static const Tint VO_NOFOLLOW = 0x00020000;
    typedef uint     Tmode_t;
    static const Tuint VS_IRUSR = 0x00000100;
    static const Tuint VS_IWUSR = 0x00000080;
    static const Tuint VS_IXUSR = 0x00000040;
    static const Tuint VS_IRGRP = 0x00000020;
    static const Tuint VS_IWGRP = 0x00000010;
    static const Tuint VS_IXGRP = 0x00000008;
    static const Tuint VS_IROTH = 0x00000004;
    static const Tuint VS_IWOTH = 0x00000002;
    static const Tuint VS_IXOTH = 0x00000001;
    static const Tint VF_DUPFD = 0x00000000;
    static const Tint VF_GETFD = 0x00000001;
    static const Tint VF_SETFD = 0x00000002;
    static const Tint VF_GETFL = 0x00000003;
    static const Tint VF_SETFL = 0x00000004;
    static const Tint VFD_CLOEXEC = 0x00000001;
    class Tiovec {
    public:
        static const size_t Size_All=8;
        typedef Tpointer_t Type_iov_base;
        static const size_t Offs_iov_base=0;
        typedef Tsize_t Type_iov_len;
        static const size_t Offs_iov_len=4;
    };
    typedef int32_t  Toff_t;
    typedef int64_t  Tloff_t;
    static const Tint VSEEK_SET = 0x00000000;
    static const Tint VSEEK_CUR = 0x00000001;
    static const Tint VSEEK_END = 0x00000002;
    typedef uint32_t Tino_t;
    typedef uint64_t Tino64_t;
    typedef int64_t  Toff64_t;
    class Tdirent {
    public:
        static const size_t Size_All=268;
        typedef Tulong Type_d_ino;
        static const size_t Offs_d_ino=0;
        typedef Tulong Type_d_off;
        static const size_t Offs_d_off=4;
        typedef Tushort Type_d_reclen;
        static const size_t Offs_d_reclen=8;
        typedef Tchar Type_d_name;
        static const size_t Offs_d_name=10;
        static const size_t Step_d_name=1;
        static const size_t Size_d_name=256;
    };
    class Tdirent64 {
    public:
        static const size_t Size_All=280;
        typedef Tino64_t Type_d_ino;
        static const size_t Offs_d_ino=0;
        typedef Toff64_t Type_d_off;
        static const size_t Offs_d_off=8;
        typedef Tushort Type_d_reclen;
        static const size_t Offs_d_reclen=16;
        typedef Tuchar Type_d_type;
        static const size_t Offs_d_type=18;
        typedef Tchar Type_d_name;
        static const size_t Offs_d_name=19;
        static const size_t Step_d_name=1;
        static const size_t Size_d_name=256;
    };
    static const Tint VTCGETS = 0x0000540d;
    static const Tint VTCSETS = 0x0000540e;
    static const Tint VTCSETSW = 0x0000540f;
    static const Tint VTCSETSF = 0x00005410;
    static const Tint VTCGETA = 0x00005401;
    static const Tint VTCSETA = 0x00005402;
    static const Tint VTCSETAW = 0x00005403;
    static const Tint VTCSETAF = 0x00005404;
    static const Tlong VTIOCGWINSZ = 0x40087468;
    class Twinsize {
    public:
        static const size_t Size_All=8;
        typedef Tushort Type_ws_row;
        static const size_t Offs_ws_row=0;
        typedef Tushort Type_ws_col;
        static const size_t Offs_ws_col=2;
        typedef Tushort Type_ws_xpixel;
        static const size_t Offs_ws_xpixel=4;
        typedef Tushort Type_ws_ypixel;
        static const size_t Offs_ws_ypixel=6;
    };
    class Tpollfd {
    public:
        static const size_t Size_All=8;
        typedef Tint Type_fd;
        static const size_t Offs_fd=0;
        typedef Tshort Type_events;
        static const size_t Offs_events=4;
        typedef Tshort Type_revents;
        static const size_t Offs_revents=6;
    };
    static const Tint VPOLLIN = 0x00000001;
    static const Tint VPOLLPRI = 0x00000002;
    static const Tint VPOLLOUT = 0x00000004;
    static const Tint VPOLLERR = 0x00000008;
    static const Tint VPOLLHUP = 0x00000010;
    static const Tint VPOLLNVAL = 0x00000020;
    typedef uint32_t Tst_dev_t;
    typedef uint64_t Tst_ino_t;
    typedef uint32_t Tst_nlink_t;
    typedef int64_t  Tst_size_t;
    typedef uint32_t Tst_blksize_t;
    typedef int64_t  Tst_blocks_t;
    class Tstat {
    public:
        static const size_t Size_All=104;
        typedef Tst_dev_t Type_st_dev;
        static const size_t Offs_st_dev=0;
        typedef Tst_ino_t Type_st_ino;
        static const size_t Offs_st_ino=16;
        typedef Tmode_t Type_st_mode;
        static const size_t Offs_st_mode=24;
        typedef Tst_nlink_t Type_st_nlink;
        static const size_t Offs_st_nlink=28;
        typedef Tuid_t Type_st_uid;
        static const size_t Offs_st_uid=32;
        typedef Tgid_t Type_st_gid;
        static const size_t Offs_st_gid=36;
        typedef Tst_dev_t Type_st_rdev;
        static const size_t Offs_st_rdev=40;
        typedef Tst_size_t Type_st_size;
        static const size_t Offs_st_size=56;
        typedef Tuint Type_st_atime_sec;
        static const size_t Offs_st_atime_sec=64;
        typedef Tuint Type_st_mtime_sec;
        static const size_t Offs_st_mtime_sec=72;
        typedef Tuint Type_st_ctime_sec;
        static const size_t Offs_st_ctime_sec=80;
        typedef Tst_blksize_t Type_st_blksize;
        static const size_t Offs_st_blksize=88;
        typedef Tst_blocks_t Type_st_blocks;
        static const size_t Offs_st_blocks=96;
    };
    typedef uint32_t Tnlink_t;
    typedef int32_t  Tblksize_t;
    typedef int64_t  Tblkcnt64_t;
    typedef uint32_t Tst_dev64_t;
    class Tstat64 {
    public:
        static const size_t Size_All=160;
        typedef Tst_dev64_t Type_st_dev;
        static const size_t Offs_st_dev=0;
        typedef Tino64_t Type_st_ino;
        static const size_t Offs_st_ino=16;
        typedef Tmode_t Type_st_mode;
        static const size_t Offs_st_mode=24;
        typedef Tnlink_t Type_st_nlink;
        static const size_t Offs_st_nlink=28;
        typedef Tuid_t Type_st_uid;
        static const size_t Offs_st_uid=32;
        typedef Tgid_t Type_st_gid;
        static const size_t Offs_st_gid=36;
        typedef Tst_dev64_t Type_st_rdev;
        static const size_t Offs_st_rdev=40;
        typedef Toff64_t Type_st_size;
        static const size_t Offs_st_size=56;
        typedef Ttime_t Type_st_atime;
        static const size_t Offs_st_atime=64;
        typedef Ttime_t Type_st_mtime;
        static const size_t Offs_st_mtime=72;
        typedef Ttime_t Type_st_ctime;
        static const size_t Offs_st_ctime=80;
        typedef Tblksize_t Type_st_blksize;
        static const size_t Offs_st_blksize=88;
        typedef Tblkcnt64_t Type_st_blocks;
        static const size_t Offs_st_blocks=96;
    };
    static const Tint VF_OK = 0x00000000;
    static const Tint VR_OK = 0x00000004;
    static const Tint VW_OK = 0x00000002;
    static const Tint VX_OK = 0x00000001;
    typedef uint32_t Trlim_t;
    class Trlimit {
    public:
        static const size_t Size_All=8;
        typedef Trlim_t Type_rlim_cur;
        static const size_t Offs_rlim_cur=0;
        typedef Trlim_t Type_rlim_max;
        static const size_t Offs_rlim_max=4;
    };
    static const Tint VRLIMIT_AS = 0x00000006;
    static const Tint VRLIMIT_CORE = 0x00000004;
    static const Tint VRLIMIT_CPU = 0x00000000;
    static const Tint VRLIMIT_DATA = 0x00000002;
    static const Tint VRLIMIT_FSIZE = 0x00000001;
    static const Tint VRLIMIT_LOCKS = 0x0000000a;
    static const Tint VRLIMIT_MEMLOCK = 0x00000009;
    static const Tint VRLIMIT_NOFILE = 0x00000005;
    static const Tint VRLIMIT_NPROC = 0x00000008;
    static const Tint VRLIMIT_RSS = 0x00000007;
    static const Tint VRLIMIT_STACK = 0x00000003;
    static const Trlim_t VRLIM_INFINITY = 0x7fffffff;
    class Trusage {
    public:
        static const size_t Size_All=72;
        typedef Ttimeval Type_ru_utime;
        static const size_t Offs_ru_utime=0;
        typedef Ttimeval Type_ru_stime;
        static const size_t Offs_ru_stime=8;
        typedef Tlong Type_ru_maxrss;
        static const size_t Offs_ru_maxrss=16;
        typedef Tlong Type_ru_ixrss;
        static const size_t Offs_ru_ixrss=20;
        typedef Tlong Type_ru_idrss;
        static const size_t Offs_ru_idrss=24;
        typedef Tlong Type_ru_isrss;
        static const size_t Offs_ru_isrss=28;
        typedef Tlong Type_ru_minflt;
        static const size_t Offs_ru_minflt=32;
        typedef Tlong Type_ru_majflt;
        static const size_t Offs_ru_majflt=36;
        typedef Tlong Type_ru_nswap;
        static const size_t Offs_ru_nswap=40;
        typedef Tlong Type_ru_inblock;
        static const size_t Offs_ru_inblock=44;
        typedef Tlong Type_ru_oublock;
        static const size_t Offs_ru_oublock=48;
        typedef Tlong Type_ru_msgsnd;
        static const size_t Offs_ru_msgsnd=52;
        typedef Tlong Type_ru_msgrcv;
        static const size_t Offs_ru_msgrcv=56;
        typedef Tlong Type_ru_nsignals;
        static const size_t Offs_ru_nsignals=60;
        typedef Tlong Type_ru_nvcsw;
        static const size_t Offs_ru_nvcsw=64;
        typedef Tlong Type_ru_nivcsw;
        static const size_t Offs_ru_nivcsw=68;
    };
    static const Tint VRUSAGE_SELF = 0x00000000;
    static const Tint VRUSAGE_CHILDREN = ~Tint(0x00000000);
    class Tutsname {
    public:
        static const size_t Size_All=390;
        typedef Tchar Type_sysname;
        static const size_t Offs_sysname=0;
        static const size_t Step_sysname=1;
        static const size_t Size_sysname=65;
        typedef Tchar Type_nodename;
        static const size_t Offs_nodename=65;
        static const size_t Step_nodename=1;
        static const size_t Size_nodename=65;
        typedef Tchar Type_release;
        static const size_t Offs_release=130;
        static const size_t Step_release=1;
        static const size_t Size_release=65;
        typedef Tchar Type_version;
        static const size_t Offs_version=195;
        static const size_t Step_version=1;
        static const size_t Size_version=65;
        typedef Tchar Type_machine;
        static const size_t Offs_machine=260;
        static const size_t Step_machine=1;
        static const size_t Size_machine=65;
    };
    class T__sysctl_args {
    public:
        static const size_t Size_All=40;
        typedef Tpointer_t Type_name;
        static const size_t Offs_name=0;
        typedef Tint Type_nlen;
        static const size_t Offs_nlen=4;
        typedef Tpointer_t Type_oldval;
        static const size_t Offs_oldval=8;
        typedef Tpointer_t Type_oldlenp;
        static const size_t Offs_oldlenp=12;
        typedef Tpointer_t Type_newval;
        static const size_t Offs_newval=16;
        typedef Tsize_t Type_newlen;
        static const size_t Offs_newlen=20;
    };
    static const Tint VCTL_KERN = 0x00000001;
    static const Tint VKERN_VERSION = 0x00000004;
    class Tsigset_t {
    public:
        static const size_t Size_All=16;
        typedef Tulong Type_sig;
        static const size_t Offs_sig=0;
        static const size_t Step_sig=4;
        static const size_t Size_sig=4;
    };
    class Tsigaction {
    public:
        static const size_t Size_All=24;
        typedef Tuint Type_sa_flags;
        static const size_t Offs_sa_flags=0;
        typedef Tpointer_t Type_sa_handler;
        static const size_t Offs_sa_handler=4;
        typedef Tsigset_t Type_sa_mask;
        static const size_t Offs_sa_mask=8;
    };

    // curl --silent https://raw.githubusercontent.com/hrw/syscalls-table/master/tables/syscalls-mipso32 | awk '/\s[0-9]/ { print "\tstatic const Tint V__NR_" $1, "=", $2 ";" }'
    static const Tint V__NR__llseek = 4140;
    static const Tint V__NR__newselect = 4142;
    static const Tint V__NR__sysctl = 4153;
    static const Tint V__NR_accept = 4168;
    static const Tint V__NR_accept4 = 4334;
    static const Tint V__NR_access = 4033;
    static const Tint V__NR_acct = 4051;
    static const Tint V__NR_add_key = 4280;
    static const Tint V__NR_adjtimex = 4124;
    static const Tint V__NR_alarm = 4027;
    static const Tint V__NR_bdflush = 4134;
    static const Tint V__NR_bind = 4169;
    static const Tint V__NR_bpf = 4355;
    static const Tint V__NR_brk = 4045;
    static const Tint V__NR_cachectl = 4148;
    static const Tint V__NR_cacheflush = 4147;
    static const Tint V__NR_capget = 4204;
    static const Tint V__NR_capset = 4205;
    static const Tint V__NR_chdir = 4012;
    static const Tint V__NR_chmod = 4015;
    static const Tint V__NR_chown = 4202;
    static const Tint V__NR_chroot = 4061;
    static const Tint V__NR_clock_adjtime = 4341;
    static const Tint V__NR_clock_adjtime64 = 4405;
    static const Tint V__NR_clock_getres = 4264;
    static const Tint V__NR_clock_getres_time64 = 4406;
    static const Tint V__NR_clock_gettime = 4263;
    static const Tint V__NR_clock_gettime64 = 4403;
    static const Tint V__NR_clock_nanosleep = 4265;
    static const Tint V__NR_clock_nanosleep_time64 = 4407;
    static const Tint V__NR_clock_settime = 4262;
    static const Tint V__NR_clock_settime64 = 4404;
    static const Tint V__NR_clone = 4120;
    static const Tint V__NR_clone3 = 4435;
    static const Tint V__NR_close = 4006;
    static const Tint V__NR_close_range = 4436;
    static const Tint V__NR_connect = 4170;
    static const Tint V__NR_copy_file_range = 4360;
    static const Tint V__NR_creat = 4008;
    static const Tint V__NR_create_module = 4127;
    static const Tint V__NR_delete_module = 4129;
    static const Tint V__NR_dup = 4041;
    static const Tint V__NR_dup2 = 4063;
    static const Tint V__NR_dup3 = 4327;
    static const Tint V__NR_epoll_create = 4248;
    static const Tint V__NR_epoll_create1 = 4326;
    static const Tint V__NR_epoll_ctl = 4249;
    static const Tint V__NR_epoll_pwait = 4313;
    static const Tint V__NR_epoll_pwait2 = 4441;
    static const Tint V__NR_epoll_wait = 4250;
    static const Tint V__NR_eventfd = 4319;
    static const Tint V__NR_eventfd2 = 4325;
    static const Tint V__NR_execve = 4011;
    static const Tint V__NR_execveat = 4356;
    static const Tint V__NR_exit = 4001;
    static const Tint V__NR_exit_group = 4246;
    static const Tint V__NR_faccessat = 4300;
    static const Tint V__NR_faccessat2 = 4439;
    static const Tint V__NR_fadvise64 = 4254;
    static const Tint V__NR_fallocate = 4320;
    static const Tint V__NR_fanotify_init = 4336;
    static const Tint V__NR_fanotify_mark = 4337;
    static const Tint V__NR_fchdir = 4133;
    static const Tint V__NR_fchmod = 4094;
    static const Tint V__NR_fchmodat = 4299;
    static const Tint V__NR_fchown = 4095;
    static const Tint V__NR_fchownat = 4291;
    static const Tint V__NR_fcntl = 4055;
    static const Tint V__NR_fcntl64 = 4220;
    static const Tint V__NR_fdatasync = 4152;
    static const Tint V__NR_fgetxattr = 4229;
    static const Tint V__NR_finit_module = 4348;
    static const Tint V__NR_flistxattr = 4232;
    static const Tint V__NR_flock = 4143;
    static const Tint V__NR_fork = 4002;
    static const Tint V__NR_fremovexattr = 4235;
    static const Tint V__NR_fsconfig = 4431;
    static const Tint V__NR_fsetxattr = 4226;
    static const Tint V__NR_fsmount = 4432;
    static const Tint V__NR_fsopen = 4430;
    static const Tint V__NR_fspick = 4433;
    static const Tint V__NR_fstat = 4108;
    static const Tint V__NR_fstat64 = 4215;
    static const Tint V__NR_fstatat64 = 4293;
    static const Tint V__NR_fstatfs = 4100;
    static const Tint V__NR_fstatfs64 = 4256;
    static const Tint V__NR_fsync = 4118;
    static const Tint V__NR_ftruncate = 4093;
    static const Tint V__NR_ftruncate64 = 4212;
    static const Tint V__NR_futex = 4238;
    static const Tint V__NR_futex_time64 = 4422;
    static const Tint V__NR_futimesat = 4292;
    static const Tint V__NR_get_kernel_syms = 4130;
    static const Tint V__NR_get_mempolicy = 4269;
    static const Tint V__NR_get_robust_list = 4310;
    static const Tint V__NR_getcpu = 4312;
    static const Tint V__NR_getcwd = 4203;
    static const Tint V__NR_getdents = 4141;
    static const Tint V__NR_getdents64 = 4219;
    static const Tint V__NR_getegid = 4050;
    static const Tint V__NR_geteuid = 4049;
    static const Tint V__NR_getgid = 4047;
    static const Tint V__NR_getgroups = 4080;
    static const Tint V__NR_getitimer = 4105;
    static const Tint V__NR_getpeername = 4171;
    static const Tint V__NR_getpgid = 4132;
    static const Tint V__NR_getpgrp = 4065;
    static const Tint V__NR_getpid = 4020;
    static const Tint V__NR_getpmsg = 4208;
    static const Tint V__NR_getppid = 4064;
    static const Tint V__NR_getpriority = 4096;
    static const Tint V__NR_getrandom = 4353;
    static const Tint V__NR_getresgid = 4191;
    static const Tint V__NR_getresuid = 4186;
    static const Tint V__NR_getrlimit = 4076;
    static const Tint V__NR_getrusage = 4077;
    static const Tint V__NR_getsid = 4151;
    static const Tint V__NR_getsockname = 4172;
    static const Tint V__NR_getsockopt = 4173;
    static const Tint V__NR_gettid = 4222;
    static const Tint V__NR_gettimeofday = 4078;
    static const Tint V__NR_getuid = 4024;
    static const Tint V__NR_getxattr = 4227;
    static const Tint V__NR_idle = 4112;
    static const Tint V__NR_init_module = 4128;
    static const Tint V__NR_inotify_add_watch = 4285;
    static const Tint V__NR_inotify_init = 4284;
    static const Tint V__NR_inotify_init1 = 4329;
    static const Tint V__NR_inotify_rm_watch = 4286;
    static const Tint V__NR_io_cancel = 4245;
    static const Tint V__NR_io_destroy = 4242;
    static const Tint V__NR_io_getevents = 4243;
    static const Tint V__NR_io_pgetevents = 4368;
    static const Tint V__NR_io_pgetevents_time64 = 4416;
    static const Tint V__NR_io_setup = 4241;
    static const Tint V__NR_io_submit = 4244;
    static const Tint V__NR_io_uring_enter = 4426;
    static const Tint V__NR_io_uring_register = 4427;
    static const Tint V__NR_io_uring_setup = 4425;
    static const Tint V__NR_ioctl = 4054;
    static const Tint V__NR_ioperm = 4101;
    static const Tint V__NR_iopl = 4110;
    static const Tint V__NR_ioprio_get = 4315;
    static const Tint V__NR_ioprio_set = 4314;
    static const Tint V__NR_ipc = 4117;
    static const Tint V__NR_kcmp = 4347;
    static const Tint V__NR_kexec_load = 4311;
    static const Tint V__NR_keyctl = 4282;
    static const Tint V__NR_kill = 4037;
    static const Tint V__NR_landlock_add_rule = 4445;
    static const Tint V__NR_landlock_create_ruleset = 4444;
    static const Tint V__NR_landlock_restrict_self = 4446;
    static const Tint V__NR_lchown = 4016;
    static const Tint V__NR_lgetxattr = 4228;
    static const Tint V__NR_link = 4009;
    static const Tint V__NR_linkat = 4296;
    static const Tint V__NR_listen = 4174;
    static const Tint V__NR_listxattr = 4230;
    static const Tint V__NR_llistxattr = 4231;
    static const Tint V__NR_lookup_dcookie = 4247;
    static const Tint V__NR_lremovexattr = 4234;
    static const Tint V__NR_lseek = 4019;
    static const Tint V__NR_lsetxattr = 4225;
    static const Tint V__NR_lstat = 4107;
    static const Tint V__NR_lstat64 = 4214;
    static const Tint V__NR_madvise = 4218;
    static const Tint V__NR_mbind = 4268;
    static const Tint V__NR_membarrier = 4358;
    static const Tint V__NR_memfd_create = 4354;
    static const Tint V__NR_migrate_pages = 4287;
    static const Tint V__NR_mincore = 4217;
    static const Tint V__NR_mkdir = 4039;
    static const Tint V__NR_mkdirat = 4289;
    static const Tint V__NR_mknod = 4014;
    static const Tint V__NR_mknodat = 4290;
    static const Tint V__NR_mlock = 4154;
    static const Tint V__NR_mlock2 = 4359;
    static const Tint V__NR_mlockall = 4156;
    static const Tint V__NR_mmap = 4090;
    static const Tint V__NR_mmap2 = 4210;
    static const Tint V__NR_modify_ldt = 4123;
    static const Tint V__NR_mount = 4021;
    static const Tint V__NR_mount_setattr = 4442;
    static const Tint V__NR_move_mount = 4429;
    static const Tint V__NR_move_pages = 4308;
    static const Tint V__NR_mprotect = 4125;
    static const Tint V__NR_mq_getsetattr = 4276;
    static const Tint V__NR_mq_notify = 4275;
    static const Tint V__NR_mq_open = 4271;
    static const Tint V__NR_mq_timedreceive = 4274;
    static const Tint V__NR_mq_timedreceive_time64 = 4419;
    static const Tint V__NR_mq_timedsend = 4273;
    static const Tint V__NR_mq_timedsend_time64 = 4418;
    static const Tint V__NR_mq_unlink = 4272;
    static const Tint V__NR_mremap = 4167;
    static const Tint V__NR_msgctl = 4402;
    static const Tint V__NR_msgget = 4399;
    static const Tint V__NR_msgrcv = 4401;
    static const Tint V__NR_msgsnd = 4400;
    static const Tint V__NR_msync = 4144;
    static const Tint V__NR_munlock = 4155;
    static const Tint V__NR_munlockall = 4157;
    static const Tint V__NR_munmap = 4091;
    static const Tint V__NR_name_to_handle_at = 4339;
    static const Tint V__NR_nanosleep = 4166;
    static const Tint V__NR_nfsservctl = 4189;
    static const Tint V__NR_nice = 4034;
    static const Tint V__NR_open = 4005;
    static const Tint V__NR_open_by_handle_at = 4340;
    static const Tint V__NR_open_tree = 4428;
    static const Tint V__NR_openat = 4288;
    static const Tint V__NR_openat2 = 4437;
    static const Tint V__NR_pause = 4029;
    static const Tint V__NR_perf_event_open = 4333;
    static const Tint V__NR_personality = 4136;
    static const Tint V__NR_pidfd_getfd = 4438;
    static const Tint V__NR_pidfd_open = 4434;
    static const Tint V__NR_pidfd_send_signal = 4424;
    static const Tint V__NR_pipe = 4042;
    static const Tint V__NR_pipe2 = 4328;
    static const Tint V__NR_pivot_root = 4216;
    static const Tint V__NR_pkey_alloc = 4364;
    static const Tint V__NR_pkey_free = 4365;
    static const Tint V__NR_pkey_mprotect = 4363;
    static const Tint V__NR_poll = 4188;
    static const Tint V__NR_ppoll = 4302;
    static const Tint V__NR_ppoll_time64 = 4414;
    static const Tint V__NR_prctl = 4192;
    static const Tint V__NR_pread64 = 4200;
    static const Tint V__NR_preadv = 4330;
    static const Tint V__NR_preadv2 = 4361;
    static const Tint V__NR_prlimit64 = 4338;
    static const Tint V__NR_process_madvise = 4440;
    static const Tint V__NR_process_vm_readv = 4345;
    static const Tint V__NR_process_vm_writev = 4346;
    static const Tint V__NR_pselect6 = 4301;
    static const Tint V__NR_pselect6_time64 = 4413;
    static const Tint V__NR_ptrace = 4026;
    static const Tint V__NR_pwrite64 = 4201;
    static const Tint V__NR_pwritev = 4331;
    static const Tint V__NR_pwritev2 = 4362;
    static const Tint V__NR_query_module = 4187;
    static const Tint V__NR_quotactl = 4131;
    static const Tint V__NR_quotactl_fd = 4443;
    static const Tint V__NR_read = 4003;
    static const Tint V__NR_readahead = 4223;
    static const Tint V__NR_readdir = 4089;
    static const Tint V__NR_readlink = 4085;
    static const Tint V__NR_readlinkat = 4298;
    static const Tint V__NR_readv = 4145;
    static const Tint V__NR_reboot = 4088;
    static const Tint V__NR_recv = 4175;
    static const Tint V__NR_recvfrom = 4176;
    static const Tint V__NR_recvmmsg = 4335;
    static const Tint V__NR_recvmmsg_time64 = 4417;
    static const Tint V__NR_recvmsg = 4177;
    static const Tint V__NR_remap_file_pages = 4251;
    static const Tint V__NR_removexattr = 4233;
    static const Tint V__NR_rename = 4038;
    static const Tint V__NR_renameat = 4295;
    static const Tint V__NR_renameat2 = 4351;
    static const Tint V__NR_request_key = 4281;
    static const Tint V__NR_restart_syscall = 4253;
    static const Tint V__NR_rmdir = 4040;
    static const Tint V__NR_rseq = 4367;
    static const Tint V__NR_rt_sigaction = 4194;
    static const Tint V__NR_rt_sigpending = 4196;
    static const Tint V__NR_rt_sigprocmask = 4195;
    static const Tint V__NR_rt_sigqueueinfo = 4198;
    static const Tint V__NR_rt_sigreturn = 4193;
    static const Tint V__NR_rt_sigsuspend = 4199;
    static const Tint V__NR_rt_sigtimedwait = 4197;
    static const Tint V__NR_rt_sigtimedwait_time64 = 4421;
    static const Tint V__NR_rt_tgsigqueueinfo = 4332;
    static const Tint V__NR_sched_get_priority_max = 4163;
    static const Tint V__NR_sched_get_priority_min = 4164;
    static const Tint V__NR_sched_getaffinity = 4240;
    static const Tint V__NR_sched_getattr = 4350;
    static const Tint V__NR_sched_getparam = 4159;
    static const Tint V__NR_sched_getscheduler = 4161;
    static const Tint V__NR_sched_rr_get_interval = 4165;
    static const Tint V__NR_sched_rr_get_interval_time64 = 4423;
    static const Tint V__NR_sched_setaffinity = 4239;
    static const Tint V__NR_sched_setattr = 4349;
    static const Tint V__NR_sched_setparam = 4158;
    static const Tint V__NR_sched_setscheduler = 4160;
    static const Tint V__NR_sched_yield = 4162;
    static const Tint V__NR_seccomp = 4352;
    static const Tint V__NR_semctl = 4394;
    static const Tint V__NR_semget = 4393;
    static const Tint V__NR_semtimedop_time64 = 4420;
    static const Tint V__NR_send = 4178;
    static const Tint V__NR_sendfile = 4207;
    static const Tint V__NR_sendfile64 = 4237;
    static const Tint V__NR_sendmmsg = 4343;
    static const Tint V__NR_sendmsg = 4179;
    static const Tint V__NR_sendto = 4180;
    static const Tint V__NR_set_mempolicy = 4270;
    static const Tint V__NR_set_robust_list = 4309;
    static const Tint V__NR_set_thread_area = 4283;
    static const Tint V__NR_set_tid_address = 4252;
    static const Tint V__NR_setdomainname = 4121;
    static const Tint V__NR_setfsgid = 4139;
    static const Tint V__NR_setfsuid = 4138;
    static const Tint V__NR_setgid = 4046;
    static const Tint V__NR_setgroups = 4081;
    static const Tint V__NR_sethostname = 4074;
    static const Tint V__NR_setitimer = 4104;
    static const Tint V__NR_setns = 4344;
    static const Tint V__NR_setpgid = 4057;
    static const Tint V__NR_setpriority = 4097;
    static const Tint V__NR_setregid = 4071;
    static const Tint V__NR_setresgid = 4190;
    static const Tint V__NR_setresuid = 4185;
    static const Tint V__NR_setreuid = 4070;
    static const Tint V__NR_setrlimit = 4075;
    static const Tint V__NR_setsid = 4066;
    static const Tint V__NR_setsockopt = 4181;
    static const Tint V__NR_settimeofday = 4079;
    static const Tint V__NR_setuid = 4023;
    static const Tint V__NR_setxattr = 4224;
    static const Tint V__NR_sgetmask = 4068;
    static const Tint V__NR_shmat = 4397;
    static const Tint V__NR_shmctl = 4396;
    static const Tint V__NR_shmdt = 4398;
    static const Tint V__NR_shmget = 4395;
    static const Tint V__NR_shutdown = 4182;
    static const Tint V__NR_sigaction = 4067;
    static const Tint V__NR_sigaltstack = 4206;
    static const Tint V__NR_signal = 4048;
    static const Tint V__NR_signalfd = 4317;
    static const Tint V__NR_signalfd4 = 4324;
    static const Tint V__NR_sigpending = 4073;
    static const Tint V__NR_sigprocmask = 4126;
    static const Tint V__NR_sigreturn = 4119;
    static const Tint V__NR_sigsuspend = 4072;
    static const Tint V__NR_socket = 4183;
    static const Tint V__NR_socketcall = 4102;
    static const Tint V__NR_socketpair = 4184;
    static const Tint V__NR_splice = 4304;
    static const Tint V__NR_ssetmask = 4069;
    static const Tint V__NR_stat = 4106;
    static const Tint V__NR_stat64 = 4213;
    static const Tint V__NR_statfs = 4099;
    static const Tint V__NR_statfs64 = 4255;
    static const Tint V__NR_statx = 4366;
    static const Tint V__NR_stime = 4025;
    static const Tint V__NR_swapoff = 4115;
    static const Tint V__NR_swapon = 4087;
    static const Tint V__NR_symlink = 4083;
    static const Tint V__NR_symlinkat = 4297;
    static const Tint V__NR_sync = 4036;
    static const Tint V__NR_sync_file_range = 4305;
    static const Tint V__NR_syncfs = 4342;
    static const Tint V__NR_syscall = 4000;
    static const Tint V__NR_sysfs = 4135;
    static const Tint V__NR_sysinfo = 4116;
    static const Tint V__NR_syslog = 4103;
    static const Tint V__NR_sysmips = 4149;
    static const Tint V__NR_tee = 4306;
    static const Tint V__NR_tgkill = 4266;
    static const Tint V__NR_time = 4013;
    static const Tint V__NR_timer_create = 4257;
    static const Tint V__NR_timer_delete = 4261;
    static const Tint V__NR_timer_getoverrun = 4260;
    static const Tint V__NR_timer_gettime = 4259;
    static const Tint V__NR_timer_gettime64 = 4408;
    static const Tint V__NR_timer_settime = 4258;
    static const Tint V__NR_timer_settime64 = 4409;
    static const Tint V__NR_timerfd = 4318;
    static const Tint V__NR_timerfd_create = 4321;
    static const Tint V__NR_timerfd_gettime = 4322;
    static const Tint V__NR_timerfd_gettime64 = 4410;
    static const Tint V__NR_timerfd_settime = 4323;
    static const Tint V__NR_timerfd_settime64 = 4411;
    static const Tint V__NR_times = 4043;
    static const Tint V__NR_tkill = 4236;
    static const Tint V__NR_truncate = 4092;
    static const Tint V__NR_truncate64 = 4211;
    static const Tint V__NR_umask = 4060;
    static const Tint V__NR_umount = 4022;
    static const Tint V__NR_umount2 = 4052;
    static const Tint V__NR_uname = 4122;
    static const Tint V__NR_unlink = 4010;
    static const Tint V__NR_unlinkat = 4294;
    static const Tint V__NR_unshare = 4303;
    static const Tint V__NR_uselib = 4086;
    static const Tint V__NR_userfaultfd = 4357;
    static const Tint V__NR_ustat = 4062;
    static const Tint V__NR_utime = 4030;
    static const Tint V__NR_utimensat = 4316;
    static const Tint V__NR_utimensat_time64 = 4412;
    static const Tint V__NR_utimes = 4267;
    static const Tint V__NR_vhangup = 4111;
    static const Tint V__NR_vm86 = 4113;
    static const Tint V__NR_vmsplice = 4307;
    static const Tint V__NR_wait4 = 4114;
    static const Tint V__NR_waitid = 4278;
    static const Tint V__NR_waitpid = 4007;
    static const Tint V__NR_write = 4004;
    static const Tint V__NR_writev = 4146;
};
