template<>
class ABIDefs<ExecModeMipsN32> {
public:
    typedef uint32_t Tpointer_t;
    typedef int8_t Tchar;
    typedef uint8_t Tuchar;
    typedef int16_t Tshort;
    typedef uint16_t Tushort;
    typedef int32_t Tint;
    typedef uint32_t Tuint;
    typedef int32_t Tlong;
    typedef uint32_t Tulong;
    typedef int64_t Tllong;
    typedef int32_t Tssize_t;
    typedef int32_t Tptrdiff_t;
    typedef uint32_t Tsize_t;
    static const Tint VSTDIN_FILENO = 0x00000000;
    static const Tint VSTDOUT_FILENO = 0x00000001;
    static const Tint VSTDERR_FILENO = 0x00000002;
    typedef int32_t Tpid_t;
    static const Tint VEPERM = 0x00000001;
    static const Tint VENOENT = 0x00000002;
    static const Tint VESRCH = 0x00000003;
    static const Tint VEINTR = 0x00000004;
    static const Tint VEIO = 0x00000005;
    static const Tint VENXIO = 0x00000006;
    static const Tint VE2BIG = 0x00000007;
    static const Tint VENOEXEC = 0x00000008;
    static const Tint VEBADF = 0x00000009;
    static const Tint VECHILD = 0x0000000a;
    static const Tint VEAGAIN = 0x0000000b;
    static const Tint VENOMEM = 0x0000000c;
    static const Tint VEACCES = 0x0000000d;
    static const Tint VEFAULT = 0x0000000e;
    static const Tint VENOTBLK = 0x0000000f;
    static const Tint VEBUSY = 0x00000010;
    static const Tint VEEXIST = 0x00000011;
    static const Tint VEXDEV = 0x00000012;
    static const Tint VENODEV = 0x00000013;
    static const Tint VENOTDIR = 0x00000014;
    static const Tint VEISDIR = 0x00000015;
    static const Tint VEINVAL = 0x00000016;
    static const Tint VENFILE = 0x00000017;
    static const Tint VEMFILE = 0x00000018;
    static const Tint VENOTTY = 0x00000019;
    static const Tint VETXTBSY = 0x0000001a;
    static const Tint VEFBIG = 0x0000001b;
    static const Tint VENOSPC = 0x0000001c;
    static const Tint VESPIPE = 0x0000001d;
    static const Tint VEROFS = 0x0000001e;
    static const Tint VEMLINK = 0x0000001f;
    static const Tint VEPIPE = 0x00000020;
    static const Tint VEDOM = 0x00000021;
    static const Tint VERANGE = 0x00000022;
    static const Tint VENOSYS = 0x00000059;
    static const Tint VEAFNOSUPPORT = 0x0000007c;
    static const Tint VSIGHUP = 0x00000001;
    static const Tint VSIGINT = 0x00000002;
    static const Tint VSIGQUIT = 0x00000003;
    static const Tint VSIGILL = 0x00000004;
    static const Tint VSIGTRAP = 0x00000005;
    static const Tint VSIGABRT = 0x00000006;
    static const Tint VSIGFPE = 0x00000008;
    static const Tint VSIGKILL = 0x00000009;
    static const Tint VSIGBUS = 0x0000000a;
    static const Tint VSIGSEGV = 0x0000000b;
    static const Tint VSIGPIPE = 0x0000000d;
    static const Tint VSIGALRM = 0x0000000e;
    static const Tint VSIGTERM = 0x0000000f;
    static const Tint VSIGUSR1 = 0x00000010;
    static const Tint VSIGUSR2 = 0x00000011;
    static const Tint VSIGCHLD = 0x00000012;
    static const Tint VSIGSTOP = 0x00000017;
    static const Tint VSIGTSTP = 0x00000018;
    static const Tint VSIGCONT = 0x00000019;
    static const Tint VCSIGNAL = 0x000000ff;
    static const Tint VCLONE_VM = 0x00000100;
    static const Tint VCLONE_FS = 0x00000200;
    static const Tint VCLONE_FILES = 0x00000400;
    static const Tint VCLONE_SIGHAND = 0x00000800;
    static const Tint VCLONE_VFORK = 0x00004000;
    static const Tint VCLONE_PARENT = 0x00008000;
    static const Tint VCLONE_THREAD = 0x00010000;
    static const Tint VCLONE_NEWNS = 0x00020000;
    static const Tint VCLONE_SYSVSEM = 0x00040000;
    static const Tint VCLONE_SETTLS = 0x00080000;
    static const Tint VCLONE_PARENT_SETTID = 0x00100000;
    static const Tint VCLONE_CHILD_CLEARTID = 0x00200000;
    static const Tint VCLONE_DETACHED = 0x00400000;
    static const Tint VCLONE_UNTRACED = 0x00800000;
    static const Tint VCLONE_CHILD_SETTID = 0x01000000;
    static const Tint VCLONE_STOPPED = 0x02000000;
    static const Tint VWNOHANG = 0x00000001;
    static const Tint VWUNTRACED = 0x00000002;
    static const Tint VFUTEX_PRIVATE_FLAG = 0x00000080;
    static const Tint VFUTEX_CMD_MASK = 0xffffff7f;
    static const Tint VFUTEX_WAIT = 0x00000000;
    static const Tint VFUTEX_WAKE = 0x00000001;
    static const Tint VFUTEX_FD = 0x00000002;
    static const Tint VFUTEX_REQUEUE = 0x00000003;
    static const Tint VFUTEX_CMP_REQUEUE = 0x00000004;
    static const Tint VFUTEX_WAKE_OP = 0x00000005;
    static const Tint VFUTEX_OP_OPARG_SHIFT = 0x00000008;
    static const Tint VFUTEX_OP_SET = 0x00000000;
    static const Tint VFUTEX_OP_ADD = 0x00000001;
    static const Tint VFUTEX_OP_OR = 0x00000002;
    static const Tint VFUTEX_OP_ANDN = 0x00000003;
    static const Tint VFUTEX_OP_XOR = 0x00000004;
    static const Tint VFUTEX_OP_CMP_EQ = 0x00000000;
    static const Tint VFUTEX_OP_CMP_NE = 0x00000001;
    static const Tint VFUTEX_OP_CMP_LT = 0x00000002;
    static const Tint VFUTEX_OP_CMP_LE = 0x00000003;
    static const Tint VFUTEX_OP_CMP_GT = 0x00000004;
    static const Tint VFUTEX_OP_CMP_GE = 0x00000005;

    class Trobust_list {
    public:
        static const size_t Size_All = 4;
        typedef Tpointer_t Type_next;
        static const size_t Offs_next = 0;
    };

    class Trobust_list_head {
    public:
        static const size_t Size_All = 12;
        typedef Trobust_list Type_list;
        static const size_t Offs_list = 0;
        typedef Tlong Type_futex_offset;
        static const size_t Offs_futex_offset = 4;
        typedef Tpointer_t Type_list_op_pending;
        static const size_t Offs_list_op_pending = 8;
    };

    static const Tint VSA_NOCLDSTOP = 0x00000001;
    static const Tint VSA_NOCLDWAIT = 0x00010000;
    static const Tuint VSA_RESETHAND = 0x80000000;
    static const Tint VSA_ONSTACK = 0x08000000;
    static const Tint VSA_SIGINFO = 0x00000008;
    static const Tint VSA_RESTART = 0x10000000;
    static const Tint VSA_NODEFER = 0x40000000;
    static const Tint VSA_INTERRUPT = 0x20000000;
    static const Tpointer_t VSIG_DFL = 0x00000000;
    static const Tpointer_t VSIG_IGN = 0x00000001;
    static const Tint VSIG_BLOCK = 0x00000001;
    static const Tint VSIG_UNBLOCK = 0x00000002;
    static const Tint VSIG_SETMASK = 0x00000003;
    typedef int32_t Tclock_t;

    class Ttms {
    public:
        static const size_t Size_All = 16;
        typedef Tclock_t Type_tms_utime;
        static const size_t Offs_tms_utime = 0;
        typedef Tclock_t Type_tms_stime;
        static const size_t Offs_tms_stime = 4;
        typedef Tclock_t Type_tms_cutime;
        static const size_t Offs_tms_cutime = 8;
        typedef Tclock_t Type_tms_cstime;
        static const size_t Offs_tms_cstime = 12;
    };

    typedef int32_t Ttime_t;
    typedef int32_t Tsuseconds_t;

    class Ttimeval {
    public:
        static const size_t Size_All = 8;
        typedef Ttime_t Type_tv_sec;
        static const size_t Offs_tv_sec = 0;
        typedef Tsuseconds_t Type_tv_usec;
        static const size_t Offs_tv_usec = 4;
    };

    class Ttimezone {
    public:
        static const size_t Size_All = 8;
        typedef Tint Type_tz_minuteswest;
        static const size_t Offs_tz_minuteswest = 0;
        typedef Tint Type_tz_dsttime;
        static const size_t Offs_tz_dsttime = 4;
    };

    typedef int32_t Tclockid_t;

    class Ttimespec {
    public:
        static const size_t Size_All = 8;
        typedef Ttime_t Type_tv_sec;
        static const size_t Offs_tv_sec = 0;
        typedef Tlong Type_tv_nsec;
        static const size_t Offs_tv_nsec = 4;
    };

    typedef uint32_t Tuid_t;
    typedef uint32_t Tgid_t;
    static const Tuint VMAP_SHARED = 0x00000001;
    static const Tuint VMAP_PRIVATE = 0x00000002;
    static const Tuint VMAP_FIXED = 0x00000010;
    static const Tuint VMAP_ANONYMOUS = 0x00000800;
    static const Tint VPROT_NONE = 0x00000000;
    static const Tint VPROT_READ = 0x00000001;
    static const Tint VPROT_WRITE = 0x00000002;
    static const Tint VPROT_EXEC = 0x00000004;
    static const Tuint VMREMAP_MAYMOVE = 0x00000001;
    static const Tuint VMREMAP_FIXED = 0x00000002;
    static const Tint VO_ACCMODE = 0x00000003;
    static const Tint VO_RDONLY = 0x00000000;
    static const Tint VO_WRONLY = 0x00000001;
    static const Tint VO_RDWR = 0x00000002;
    static const Tint VO_APPEND = 0x00000008;
    static const Tint VO_SYNC = 0x00000010;
    static const Tint VO_NONBLOCK = 0x00000080;
    static const Tint VO_CREAT = 0x00000100;
    static const Tint VO_TRUNC = 0x00000200;
    static const Tint VO_EXCL = 0x00000400;
    static const Tint VO_NOCTTY = 0x00000800;
    static const Tint VO_ASYNC = 0x00001000;
    static const Tint VO_LARGEFILE = 0x00002000;
    static const Tint VO_DIRECT = 0x00008000;
    static const Tint VO_DIRECTORY = 0x00010000;
    static const Tint VO_NOFOLLOW = 0x00020000;
    typedef uint Tmode_t;
    static const Tuint VS_IRUSR = 0x00000100;
    static const Tuint VS_IWUSR = 0x00000080;
    static const Tuint VS_IXUSR = 0x00000040;
    static const Tuint VS_IRGRP = 0x00000020;
    static const Tuint VS_IWGRP = 0x00000010;
    static const Tuint VS_IXGRP = 0x00000008;
    static const Tuint VS_IROTH = 0x00000004;
    static const Tuint VS_IWOTH = 0x00000002;
    static const Tuint VS_IXOTH = 0x00000001;
    static const Tint VF_DUPFD = 0x00000000;
    static const Tint VF_GETFD = 0x00000001;
    static const Tint VF_SETFD = 0x00000002;
    static const Tint VF_GETFL = 0x00000003;
    static const Tint VF_SETFL = 0x00000004;
    static const Tint VFD_CLOEXEC = 0x00000001;

    class Tiovec {
    public:
        static const size_t Size_All = 8;
        typedef Tpointer_t Type_iov_base;
        static const size_t Offs_iov_base = 0;
        typedef Tsize_t Type_iov_len;
        static const size_t Offs_iov_len = 4;
    };

    typedef int32_t Toff_t;
    typedef int64_t Tloff_t;
    static const Tint VSEEK_SET = 0x00000000;
    static const Tint VSEEK_CUR = 0x00000001;
    static const Tint VSEEK_END = 0x00000002;
    typedef uint32_t Tino_t;
    typedef uint64_t Tino64_t;
    typedef int64_t Toff64_t;

    class Tdirent {
    public:
        static const size_t Size_All = 268;
        typedef Tulong Type_d_ino;
        static const size_t Offs_d_ino = 0;
        typedef Tulong Type_d_off;
        static const size_t Offs_d_off = 4;
        typedef Tushort Type_d_reclen;
        static const size_t Offs_d_reclen = 8;
        typedef Tchar Type_d_name;
        static const size_t Offs_d_name = 10;
        static const size_t Step_d_name = 1;
        static const size_t Size_d_name = 256;
    };

    class Tdirent64 {
    public:
        static const size_t Size_All = 280;
        typedef Tino64_t Type_d_ino;
        static const size_t Offs_d_ino = 0;
        typedef Toff64_t Type_d_off;
        static const size_t Offs_d_off = 8;
        typedef Tushort Type_d_reclen;
        static const size_t Offs_d_reclen = 16;
        typedef Tuchar Type_d_type;
        static const size_t Offs_d_type = 18;
        typedef Tchar Type_d_name;
        static const size_t Offs_d_name = 19;
        static const size_t Step_d_name = 1;
        static const size_t Size_d_name = 256;
    };

    static const Tint VTCGETS = 0x0000540d;
    static const Tint VTCSETS = 0x0000540e;
    static const Tint VTCSETSW = 0x0000540f;
    static const Tint VTCSETSF = 0x00005410;
    static const Tint VTCGETA = 0x00005401;
    static const Tint VTCSETA = 0x00005402;
    static const Tint VTCSETAW = 0x00005403;
    static const Tint VTCSETAF = 0x00005404;
    static const Tlong VTIOCGWINSZ = 0x40087468;

    class Twinsize {
    public:
        static const size_t Size_All = 8;
        typedef Tushort Type_ws_row;
        static const size_t Offs_ws_row = 0;
        typedef Tushort Type_ws_col;
        static const size_t Offs_ws_col = 2;
        typedef Tushort Type_ws_xpixel;
        static const size_t Offs_ws_xpixel = 4;
        typedef Tushort Type_ws_ypixel;
        static const size_t Offs_ws_ypixel = 6;
    };

    class Tpollfd {
    public:
        static const size_t Size_All = 8;
        typedef Tint Type_fd;
        static const size_t Offs_fd = 0;
        typedef Tshort Type_events;
        static const size_t Offs_events = 4;
        typedef Tshort Type_revents;
        static const size_t Offs_revents = 6;
    };

    static const Tint VPOLLIN = 0x00000001;
    static const Tint VPOLLPRI = 0x00000002;
    static const Tint VPOLLOUT = 0x00000004;
    static const Tint VPOLLERR = 0x00000008;
    static const Tint VPOLLHUP = 0x00000010;
    static const Tint VPOLLNVAL = 0x00000020;
    typedef uint32_t Tst_dev_t;
    typedef uint64_t Tst_ino_t;
    typedef uint32_t Tst_nlink_t;
    typedef int64_t Tst_size_t;
    typedef uint32_t Tst_blksize_t;
    typedef int64_t Tst_blocks_t;

    class Tstat {
    public:
        static const size_t Size_All = 104;
        typedef Tst_dev_t Type_st_dev;
        static const size_t Offs_st_dev = 0;
        typedef Tst_ino_t Type_st_ino;
        static const size_t Offs_st_ino = 16;
        typedef Tmode_t Type_st_mode;
        static const size_t Offs_st_mode = 24;
        typedef Tst_nlink_t Type_st_nlink;
        static const size_t Offs_st_nlink = 28;
        typedef Tuid_t Type_st_uid;
        static const size_t Offs_st_uid = 32;
        typedef Tgid_t Type_st_gid;
        static const size_t Offs_st_gid = 36;
        typedef Tst_dev_t Type_st_rdev;
        static const size_t Offs_st_rdev = 40;
        typedef Tst_size_t Type_st_size;
        static const size_t Offs_st_size = 56;
        typedef Tuint Type_st_atime_sec;
        static const size_t Offs_st_atime_sec = 64;
        typedef Tuint Type_st_mtime_sec;
        static const size_t Offs_st_mtime_sec = 72;
        typedef Tuint Type_st_ctime_sec;
        static const size_t Offs_st_ctime_sec = 80;
        typedef Tst_blksize_t Type_st_blksize;
        static const size_t Offs_st_blksize = 88;
        typedef Tst_blocks_t Type_st_blocks;
        static const size_t Offs_st_blocks = 96;
    };

    typedef uint32_t Tnlink_t;
    typedef int32_t Tblksize_t;
    typedef int64_t Tblkcnt64_t;
    typedef uint64_t Tst_dev64_t;

    class Tstat64 {
    public:
        static const size_t Size_All = 176;
        typedef Tst_dev64_t Type_st_dev;
        static const size_t Offs_st_dev = 0;
        typedef Tino64_t Type_st_ino;
        static const size_t Offs_st_ino = 24;
        typedef Tmode_t Type_st_mode;
        static const size_t Offs_st_mode = 32;
        typedef Tnlink_t Type_st_nlink;
        static const size_t Offs_st_nlink = 36;
        typedef Tuid_t Type_st_uid;
        static const size_t Offs_st_uid = 40;
        typedef Tgid_t Type_st_gid;
        static const size_t Offs_st_gid = 44;
        typedef Tst_dev64_t Type_st_rdev;
        static const size_t Offs_st_rdev = 48;
        typedef Toff64_t Type_st_size;
        static const size_t Offs_st_size = 72;
        typedef Ttime_t Type_st_atime;
        static const size_t Offs_st_atime = 80;
        typedef Ttime_t Type_st_mtime;
        static const size_t Offs_st_mtime = 88;
        typedef Ttime_t Type_st_ctime;
        static const size_t Offs_st_ctime = 96;
        typedef Tblksize_t Type_st_blksize;
        static const size_t Offs_st_blksize = 104;
        typedef Tblkcnt64_t Type_st_blocks;
        static const size_t Offs_st_blocks = 112;
    };

    static const Tint VF_OK = 0x00000000;
    static const Tint VR_OK = 0x00000004;
    static const Tint VW_OK = 0x00000002;
    static const Tint VX_OK = 0x00000001;
    typedef uint32_t Trlim_t;

    class Trlimit {
    public:
        static const size_t Size_All = 8;
        typedef Trlim_t Type_rlim_cur;
        static const size_t Offs_rlim_cur = 0;
        typedef Trlim_t Type_rlim_max;
        static const size_t Offs_rlim_max = 4;
    };

    static const Tint VRLIMIT_AS = 0x00000006;
    static const Tint VRLIMIT_CORE = 0x00000004;
    static const Tint VRLIMIT_CPU = 0x00000000;
    static const Tint VRLIMIT_DATA = 0x00000002;
    static const Tint VRLIMIT_FSIZE = 0x00000001;
    static const Tint VRLIMIT_LOCKS = 0x0000000a;
    static const Tint VRLIMIT_MEMLOCK = 0x00000009;
    static const Tint VRLIMIT_NOFILE = 0x00000005;
    static const Tint VRLIMIT_NPROC = 0x00000008;
    static const Tint VRLIMIT_RSS = 0x00000007;
    static const Tint VRLIMIT_STACK = 0x00000003;
    static const Tlong VRLIM_INFINITY = 0x7fffffff;

    class Trusage {
    public:
        static const size_t Size_All = 72;
        typedef Ttimeval Type_ru_utime;
        static const size_t Offs_ru_utime = 0;
        typedef Ttimeval Type_ru_stime;
        static const size_t Offs_ru_stime = 8;
        typedef Tlong Type_ru_maxrss;
        static const size_t Offs_ru_maxrss = 16;
        typedef Tlong Type_ru_ixrss;
        static const size_t Offs_ru_ixrss = 20;
        typedef Tlong Type_ru_idrss;
        static const size_t Offs_ru_idrss = 24;
        typedef Tlong Type_ru_isrss;
        static const size_t Offs_ru_isrss = 28;
        typedef Tlong Type_ru_minflt;
        static const size_t Offs_ru_minflt = 32;
        typedef Tlong Type_ru_majflt;
        static const size_t Offs_ru_majflt = 36;
        typedef Tlong Type_ru_nswap;
        static const size_t Offs_ru_nswap = 40;
        typedef Tlong Type_ru_inblock;
        static const size_t Offs_ru_inblock = 44;
        typedef Tlong Type_ru_oublock;
        static const size_t Offs_ru_oublock = 48;
        typedef Tlong Type_ru_msgsnd;
        static const size_t Offs_ru_msgsnd = 52;
        typedef Tlong Type_ru_msgrcv;
        static const size_t Offs_ru_msgrcv = 56;
        typedef Tlong Type_ru_nsignals;
        static const size_t Offs_ru_nsignals = 60;
        typedef Tlong Type_ru_nvcsw;
        static const size_t Offs_ru_nvcsw = 64;
        typedef Tlong Type_ru_nivcsw;
        static const size_t Offs_ru_nivcsw = 68;
    };

    static const Tint VRUSAGE_SELF = 0x00000000;
    static const Tint VRUSAGE_CHILDREN = 0xffffffff;

    class Tutsname {
    public:
        static const size_t Size_All = 390;
        typedef Tchar Type_sysname;
        static const size_t Offs_sysname = 0;
        static const size_t Step_sysname = 1;
        static const size_t Size_sysname = 65;
        typedef Tchar Type_nodename;
        static const size_t Offs_nodename = 65;
        static const size_t Step_nodename = 1;
        static const size_t Size_nodename = 65;
        typedef Tchar Type_release;
        static const size_t Offs_release = 130;
        static const size_t Step_release = 1;
        static const size_t Size_release = 65;
        typedef Tchar Type_version;
        static const size_t Offs_version = 195;
        static const size_t Step_version = 1;
        static const size_t Size_version = 65;
        typedef Tchar Type_machine;
        static const size_t Offs_machine = 260;
        static const size_t Step_machine = 1;
        static const size_t Size_machine = 65;
    };

    class T__sysctl_args {
    public:
        static const size_t Size_All = 40;
        typedef Tpointer_t Type_name;
        static const size_t Offs_name = 0;
        typedef Tint Type_nlen;
        static const size_t Offs_nlen = 4;
        typedef Tpointer_t Type_oldval;
        static const size_t Offs_oldval = 8;
        typedef Tpointer_t Type_oldlenp;
        static const size_t Offs_oldlenp = 12;
        typedef Tpointer_t Type_newval;
        static const size_t Offs_newval = 16;
        typedef Tsize_t Type_newlen;
        static const size_t Offs_newlen = 20;
    };

    static const Tint VCTL_KERN = 0x00000001;
    static const Tint VKERN_VERSION = 0x00000004;

    class Tsigset_t {
    public:
        static const size_t Size_All = 16;
        typedef Tulong Type_sig;
        static const size_t Offs_sig = 0;
        static const size_t Step_sig = 4;
        static const size_t Size_sig = 4;
    };

    class Tsigaction {
    public:
        static const size_t Size_All = 24;
        typedef Tuint Type_sa_flags;
        static const size_t Offs_sa_flags = 0;
        typedef Tpointer_t Type_sa_handler;
        static const size_t Offs_sa_handler = 4;
        typedef Tsigset_t Type_sa_mask;
        static const size_t Offs_sa_mask = 8;
    };

    // curl --silent https://raw.githubusercontent.com/hrw/syscalls-table/master/tables/syscalls-mips64n32 | awk '/\s[0-9]/ { print "\tstatic const Tint V__NR_" $1, "=", $2 ";" }'
    static const Tint V__NR__newselect = 6022;
    static const Tint V__NR__sysctl = 6152;
    static const Tint V__NR_accept = 6042;
    static const Tint V__NR_accept4 = 6297;
    static const Tint V__NR_access = 6020;
    static const Tint V__NR_acct = 6158;
    static const Tint V__NR_add_key = 6243;
    static const Tint V__NR_adjtimex = 6154;
    static const Tint V__NR_alarm = 6037;
    static const Tint V__NR_bind = 6048;
    static const Tint V__NR_bpf = 6319;
    static const Tint V__NR_brk = 6012;
    static const Tint V__NR_cachectl = 6198;
    static const Tint V__NR_cacheflush = 6197;
    static const Tint V__NR_capget = 6123;
    static const Tint V__NR_capset = 6124;
    static const Tint V__NR_chdir = 6078;
    static const Tint V__NR_chmod = 6088;
    static const Tint V__NR_chown = 6090;
    static const Tint V__NR_chroot = 6156;
    static const Tint V__NR_clock_adjtime = 6305;
    static const Tint V__NR_clock_adjtime64 = 6405;
    static const Tint V__NR_clock_getres = 6227;
    static const Tint V__NR_clock_getres_time64 = 6406;
    static const Tint V__NR_clock_gettime = 6226;
    static const Tint V__NR_clock_gettime64 = 6403;
    static const Tint V__NR_clock_nanosleep = 6228;
    static const Tint V__NR_clock_nanosleep_time64 = 6407;
    static const Tint V__NR_clock_settime = 6225;
    static const Tint V__NR_clock_settime64 = 6404;
    static const Tint V__NR_clone = 6055;
    static const Tint V__NR_clone3 = 6435;
    static const Tint V__NR_close = 6003;
    static const Tint V__NR_close_range = 6436;
    static const Tint V__NR_connect = 6041;
    static const Tint V__NR_copy_file_range = 6324;
    static const Tint V__NR_creat = 6083;
    static const Tint V__NR_create_module = 6167;
    static const Tint V__NR_delete_module = 6169;
    static const Tint V__NR_dup = 6031;
    static const Tint V__NR_dup2 = 6032;
    static const Tint V__NR_dup3 = 6290;
    static const Tint V__NR_epoll_create = 6207;
    static const Tint V__NR_epoll_create1 = 6289;
    static const Tint V__NR_epoll_ctl = 6208;
    static const Tint V__NR_epoll_pwait = 6276;
    static const Tint V__NR_epoll_pwait2 = 6441;
    static const Tint V__NR_epoll_wait = 6209;
    static const Tint V__NR_eventfd = 6282;
    static const Tint V__NR_eventfd2 = 6288;
    static const Tint V__NR_execve = 6057;
    static const Tint V__NR_execveat = 6320;
    static const Tint V__NR_exit = 6058;
    static const Tint V__NR_exit_group = 6205;
    static const Tint V__NR_faccessat = 6263;
    static const Tint V__NR_faccessat2 = 6439;
    static const Tint V__NR_fadvise64 = 6216;
    static const Tint V__NR_fallocate = 6283;
    static const Tint V__NR_fanotify_init = 6300;
    static const Tint V__NR_fanotify_mark = 6301;
    static const Tint V__NR_fchdir = 6079;
    static const Tint V__NR_fchmod = 6089;
    static const Tint V__NR_fchmodat = 6262;
    static const Tint V__NR_fchown = 6091;
    static const Tint V__NR_fchownat = 6254;
    static const Tint V__NR_fcntl = 6070;
    static const Tint V__NR_fcntl64 = 6212;
    static const Tint V__NR_fdatasync = 6073;
    static const Tint V__NR_fgetxattr = 6185;
    static const Tint V__NR_finit_module = 6312;
    static const Tint V__NR_flistxattr = 6188;
    static const Tint V__NR_flock = 6071;
    static const Tint V__NR_fork = 6056;
    static const Tint V__NR_fremovexattr = 6191;
    static const Tint V__NR_fsconfig = 6431;
    static const Tint V__NR_fsetxattr = 6182;
    static const Tint V__NR_fsmount = 6432;
    static const Tint V__NR_fsopen = 6430;
    static const Tint V__NR_fspick = 6433;
    static const Tint V__NR_fstat = 6005;
    static const Tint V__NR_fstatfs = 6135;
    static const Tint V__NR_fstatfs64 = 6218;
    static const Tint V__NR_fsync = 6072;
    static const Tint V__NR_ftruncate = 6075;
    static const Tint V__NR_futex = 6194;
    static const Tint V__NR_futex_time64 = 6422;
    static const Tint V__NR_futimesat = 6255;
    static const Tint V__NR_get_kernel_syms = 6170;
    static const Tint V__NR_get_mempolicy = 6232;
    static const Tint V__NR_get_robust_list = 6273;
    static const Tint V__NR_getcpu = 6275;
    static const Tint V__NR_getcwd = 6077;
    static const Tint V__NR_getdents = 6076;
    static const Tint V__NR_getdents64 = 6299;
    static const Tint V__NR_getegid = 6106;
    static const Tint V__NR_geteuid = 6105;
    static const Tint V__NR_getgid = 6102;
    static const Tint V__NR_getgroups = 6113;
    static const Tint V__NR_getitimer = 6035;
    static const Tint V__NR_getpeername = 6051;
    static const Tint V__NR_getpgid = 6119;
    static const Tint V__NR_getpgrp = 6109;
    static const Tint V__NR_getpid = 6038;
    static const Tint V__NR_getpmsg = 6174;
    static const Tint V__NR_getppid = 6108;
    static const Tint V__NR_getpriority = 6137;
    static const Tint V__NR_getrandom = 6317;
    static const Tint V__NR_getresgid = 6118;
    static const Tint V__NR_getresuid = 6116;
    static const Tint V__NR_getrlimit = 6095;
    static const Tint V__NR_getrusage = 6096;
    static const Tint V__NR_getsid = 6122;
    static const Tint V__NR_getsockname = 6050;
    static const Tint V__NR_getsockopt = 6054;
    static const Tint V__NR_gettid = 6178;
    static const Tint V__NR_gettimeofday = 6094;
    static const Tint V__NR_getuid = 6100;
    static const Tint V__NR_getxattr = 6183;
    static const Tint V__NR_init_module = 6168;
    static const Tint V__NR_inotify_add_watch = 6248;
    static const Tint V__NR_inotify_init = 6247;
    static const Tint V__NR_inotify_init1 = 6292;
    static const Tint V__NR_inotify_rm_watch = 6249;
    static const Tint V__NR_io_cancel = 6204;
    static const Tint V__NR_io_destroy = 6201;
    static const Tint V__NR_io_getevents = 6202;
    static const Tint V__NR_io_pgetevents = 6332;
    static const Tint V__NR_io_pgetevents_time64 = 6416;
    static const Tint V__NR_io_setup = 6200;
    static const Tint V__NR_io_submit = 6203;
    static const Tint V__NR_io_uring_enter = 6426;
    static const Tint V__NR_io_uring_register = 6427;
    static const Tint V__NR_io_uring_setup = 6425;
    static const Tint V__NR_ioctl = 6015;
    static const Tint V__NR_ioprio_get = 6278;
    static const Tint V__NR_ioprio_set = 6277;
    static const Tint V__NR_kcmp = 6311;
    static const Tint V__NR_kexec_load = 6274;
    static const Tint V__NR_keyctl = 6245;
    static const Tint V__NR_kill = 6060;
    static const Tint V__NR_landlock_add_rule = 6445;
    static const Tint V__NR_landlock_create_ruleset = 6444;
    static const Tint V__NR_landlock_restrict_self = 6446;
    static const Tint V__NR_lchown = 6092;
    static const Tint V__NR_lgetxattr = 6184;
    static const Tint V__NR_link = 6084;
    static const Tint V__NR_linkat = 6259;
    static const Tint V__NR_listen = 6049;
    static const Tint V__NR_listxattr = 6186;
    static const Tint V__NR_llistxattr = 6187;
    static const Tint V__NR_lookup_dcookie = 6206;
    static const Tint V__NR_lremovexattr = 6190;
    static const Tint V__NR_lseek = 6008;
    static const Tint V__NR_lsetxattr = 6181;
    static const Tint V__NR_lstat = 6006;
    static const Tint V__NR_madvise = 6027;
    static const Tint V__NR_mbind = 6231;
    static const Tint V__NR_membarrier = 6322;
    static const Tint V__NR_memfd_create = 6318;
    static const Tint V__NR_migrate_pages = 6250;
    static const Tint V__NR_mincore = 6026;
    static const Tint V__NR_mkdir = 6081;
    static const Tint V__NR_mkdirat = 6252;
    static const Tint V__NR_mknod = 6131;
    static const Tint V__NR_mknodat = 6253;
    static const Tint V__NR_mlock = 6146;
    static const Tint V__NR_mlock2 = 6323;
    static const Tint V__NR_mlockall = 6148;
    static const Tint V__NR_mmap = 6009;
    static const Tint V__NR_mount = 6160;
    static const Tint V__NR_mount_setattr = 6442;
    static const Tint V__NR_move_mount = 6429;
    static const Tint V__NR_move_pages = 6271;
    static const Tint V__NR_mprotect = 6010;
    static const Tint V__NR_mq_getsetattr = 6239;
    static const Tint V__NR_mq_notify = 6238;
    static const Tint V__NR_mq_open = 6234;
    static const Tint V__NR_mq_timedreceive = 6237;
    static const Tint V__NR_mq_timedreceive_time64 = 6419;
    static const Tint V__NR_mq_timedsend = 6236;
    static const Tint V__NR_mq_timedsend_time64 = 6418;
    static const Tint V__NR_mq_unlink = 6235;
    static const Tint V__NR_mremap = 6024;
    static const Tint V__NR_msgctl = 6069;
    static const Tint V__NR_msgget = 6066;
    static const Tint V__NR_msgrcv = 6068;
    static const Tint V__NR_msgsnd = 6067;
    static const Tint V__NR_msync = 6025;
    static const Tint V__NR_munlock = 6147;
    static const Tint V__NR_munlockall = 6149;
    static const Tint V__NR_munmap = 6011;
    static const Tint V__NR_name_to_handle_at = 6303;
    static const Tint V__NR_nanosleep = 6034;
    static const Tint V__NR_newfstatat = 6256;
    static const Tint V__NR_nfsservctl = 6173;
    static const Tint V__NR_open = 6002;
    static const Tint V__NR_open_by_handle_at = 6304;
    static const Tint V__NR_open_tree = 6428;
    static const Tint V__NR_openat = 6251;
    static const Tint V__NR_openat2 = 6437;
    static const Tint V__NR_pause = 6033;
    static const Tint V__NR_perf_event_open = 6296;
    static const Tint V__NR_personality = 6132;
    static const Tint V__NR_pidfd_getfd = 6438;
    static const Tint V__NR_pidfd_open = 6434;
    static const Tint V__NR_pidfd_send_signal = 6424;
    static const Tint V__NR_pipe = 6021;
    static const Tint V__NR_pipe2 = 6291;
    static const Tint V__NR_pivot_root = 6151;
    static const Tint V__NR_pkey_alloc = 6328;
    static const Tint V__NR_pkey_free = 6329;
    static const Tint V__NR_pkey_mprotect = 6327;
    static const Tint V__NR_poll = 6007;
    static const Tint V__NR_ppoll = 6265;
    static const Tint V__NR_ppoll_time64 = 6414;
    static const Tint V__NR_prctl = 6153;
    static const Tint V__NR_pread64 = 6016;
    static const Tint V__NR_preadv = 6293;
    static const Tint V__NR_preadv2 = 6325;
    static const Tint V__NR_prlimit64 = 6302;
    static const Tint V__NR_process_madvise = 6440;
    static const Tint V__NR_process_vm_readv = 6309;
    static const Tint V__NR_process_vm_writev = 6310;
    static const Tint V__NR_pselect6 = 6264;
    static const Tint V__NR_pselect6_time64 = 6413;
    static const Tint V__NR_ptrace = 6099;
    static const Tint V__NR_pwrite64 = 6017;
    static const Tint V__NR_pwritev = 6294;
    static const Tint V__NR_pwritev2 = 6326;
    static const Tint V__NR_query_module = 6171;
    static const Tint V__NR_quotactl = 6172;
    static const Tint V__NR_quotactl_fd = 6443;
    static const Tint V__NR_read = 6000;
    static const Tint V__NR_readahead = 6179;
    static const Tint V__NR_readlink = 6087;
    static const Tint V__NR_readlinkat = 6261;
    static const Tint V__NR_readv = 6018;
    static const Tint V__NR_reboot = 6164;
    static const Tint V__NR_recvfrom = 6044;
    static const Tint V__NR_recvmmsg = 6298;
    static const Tint V__NR_recvmmsg_time64 = 6417;
    static const Tint V__NR_recvmsg = 6046;
    static const Tint V__NR_remap_file_pages = 6210;
    static const Tint V__NR_removexattr = 6189;
    static const Tint V__NR_rename = 6080;
    static const Tint V__NR_renameat = 6258;
    static const Tint V__NR_renameat2 = 6315;
    static const Tint V__NR_request_key = 6244;
    static const Tint V__NR_restart_syscall = 6214;
    static const Tint V__NR_rmdir = 6082;
    static const Tint V__NR_rseq = 6331;
    static const Tint V__NR_rt_sigaction = 6013;
    static const Tint V__NR_rt_sigpending = 6125;
    static const Tint V__NR_rt_sigprocmask = 6014;
    static const Tint V__NR_rt_sigqueueinfo = 6127;
    static const Tint V__NR_rt_sigreturn = 6211;
    static const Tint V__NR_rt_sigsuspend = 6128;
    static const Tint V__NR_rt_sigtimedwait = 6126;
    static const Tint V__NR_rt_sigtimedwait_time64 = 6421;
    static const Tint V__NR_rt_tgsigqueueinfo = 6295;
    static const Tint V__NR_sched_get_priority_max = 6143;
    static const Tint V__NR_sched_get_priority_min = 6144;
    static const Tint V__NR_sched_getaffinity = 6196;
    static const Tint V__NR_sched_getattr = 6314;
    static const Tint V__NR_sched_getparam = 6140;
    static const Tint V__NR_sched_getscheduler = 6142;
    static const Tint V__NR_sched_rr_get_interval = 6145;
    static const Tint V__NR_sched_rr_get_interval_time64 = 6423;
    static const Tint V__NR_sched_setaffinity = 6195;
    static const Tint V__NR_sched_setattr = 6313;
    static const Tint V__NR_sched_setparam = 6139;
    static const Tint V__NR_sched_setscheduler = 6141;
    static const Tint V__NR_sched_yield = 6023;
    static const Tint V__NR_seccomp = 6316;
    static const Tint V__NR_semctl = 6064;
    static const Tint V__NR_semget = 6062;
    static const Tint V__NR_semop = 6063;
    static const Tint V__NR_semtimedop = 6215;
    static const Tint V__NR_semtimedop_time64 = 6420;
    static const Tint V__NR_sendfile = 6039;
    static const Tint V__NR_sendfile64 = 6219;
    static const Tint V__NR_sendmmsg = 6307;
    static const Tint V__NR_sendmsg = 6045;
    static const Tint V__NR_sendto = 6043;
    static const Tint V__NR_set_mempolicy = 6233;
    static const Tint V__NR_set_robust_list = 6272;
    static const Tint V__NR_set_thread_area = 6246;
    static const Tint V__NR_set_tid_address = 6213;
    static const Tint V__NR_setdomainname = 6166;
    static const Tint V__NR_setfsgid = 6121;
    static const Tint V__NR_setfsuid = 6120;
    static const Tint V__NR_setgid = 6104;
    static const Tint V__NR_setgroups = 6114;
    static const Tint V__NR_sethostname = 6165;
    static const Tint V__NR_setitimer = 6036;
    static const Tint V__NR_setns = 6308;
    static const Tint V__NR_setpgid = 6107;
    static const Tint V__NR_setpriority = 6138;
    static const Tint V__NR_setregid = 6112;
    static const Tint V__NR_setresgid = 6117;
    static const Tint V__NR_setresuid = 6115;
    static const Tint V__NR_setreuid = 6111;
    static const Tint V__NR_setrlimit = 6155;
    static const Tint V__NR_setsid = 6110;
    static const Tint V__NR_setsockopt = 6053;
    static const Tint V__NR_settimeofday = 6159;
    static const Tint V__NR_setuid = 6103;
    static const Tint V__NR_setxattr = 6180;
    static const Tint V__NR_shmat = 6029;
    static const Tint V__NR_shmctl = 6030;
    static const Tint V__NR_shmdt = 6065;
    static const Tint V__NR_shmget = 6028;
    static const Tint V__NR_shutdown = 6047;
    static const Tint V__NR_sigaltstack = 6129;
    static const Tint V__NR_signalfd = 6280;
    static const Tint V__NR_signalfd4 = 6287;
    static const Tint V__NR_socket = 6040;
    static const Tint V__NR_socketpair = 6052;
    static const Tint V__NR_splice = 6267;
    static const Tint V__NR_stat = 6004;
    static const Tint V__NR_statfs = 6134;
    static const Tint V__NR_statfs64 = 6217;
    static const Tint V__NR_statx = 6330;
    static const Tint V__NR_swapoff = 6163;
    static const Tint V__NR_swapon = 6162;
    static const Tint V__NR_symlink = 6086;
    static const Tint V__NR_symlinkat = 6260;
    static const Tint V__NR_sync = 6157;
    static const Tint V__NR_sync_file_range = 6268;
    static const Tint V__NR_syncfs = 6306;
    static const Tint V__NR_sysfs = 6136;
    static const Tint V__NR_sysinfo = 6097;
    static const Tint V__NR_syslog = 6101;
    static const Tint V__NR_sysmips = 6199;
    static const Tint V__NR_tee = 6269;
    static const Tint V__NR_tgkill = 6229;
    static const Tint V__NR_timer_create = 6220;
    static const Tint V__NR_timer_delete = 6224;
    static const Tint V__NR_timer_getoverrun = 6223;
    static const Tint V__NR_timer_gettime = 6222;
    static const Tint V__NR_timer_gettime64 = 6408;
    static const Tint V__NR_timer_settime = 6221;
    static const Tint V__NR_timer_settime64 = 6409;
    static const Tint V__NR_timerfd = 6281;
    static const Tint V__NR_timerfd_create = 6284;
    static const Tint V__NR_timerfd_gettime = 6285;
    static const Tint V__NR_timerfd_gettime64 = 6410;
    static const Tint V__NR_timerfd_settime = 6286;
    static const Tint V__NR_timerfd_settime64 = 6411;
    static const Tint V__NR_times = 6098;
    static const Tint V__NR_tkill = 6192;
    static const Tint V__NR_truncate = 6074;
    static const Tint V__NR_umask = 6093;
    static const Tint V__NR_umount2 = 6161;
    static const Tint V__NR_uname = 6061;
    static const Tint V__NR_unlink = 6085;
    static const Tint V__NR_unlinkat = 6257;
    static const Tint V__NR_unshare = 6266;
    static const Tint V__NR_userfaultfd = 6321;
    static const Tint V__NR_ustat = 6133;
    static const Tint V__NR_utime = 6130;
    static const Tint V__NR_utimensat = 6279;
    static const Tint V__NR_utimensat_time64 = 6412;
    static const Tint V__NR_utimes = 6230;
    static const Tint V__NR_vhangup = 6150;
    static const Tint V__NR_vmsplice = 6270;
    static const Tint V__NR_wait4 = 6059;
    static const Tint V__NR_waitid = 6241;
    static const Tint V__NR_write = 6001;
    static const Tint V__NR_writev = 6019;
};
